hw 1
Arilonchik/RecoServiceTemplate pull request #1
Opened 2022-11-21 19:06 UTC by Yuki-53

2022-11-25 17:36 UTC, groundmax requested changes
Код хороший, но можно сделать лучше, после изменений внесу баллы в таблицу)

2022-11-25 17:36 UTC, groundmax commented on service/api/views.py
> +# print(API_KEY)
Если код не нужен, лучше его сразу удалять, чтобы не оставалось мусора

2022-11-25 17:36 UTC, groundmax commented on tests/api/test_views.py
> +from requests.structures import CaseInsensitiveDict
Можно же обойтись без этого, зачем он здесь?

2022-11-25 17:36 UTC, groundmax commented on service/api/views.py
> +async def check_key(
Лучше добавить type hinting на return

2022-11-25 18:40 UTC, Yuki-53 commented on tests/api/test_views.py
> +from requests.structures import CaseInsensitiveDict
Да, без этого работает, просто выпадало предупреждение, что следует использовать это

2022-11-25 19:06 UTC, Yuki-53 commented on service/api/views.py
> +# print(API_KEY)
Удалил

2022-11-25 19:06 UTC, Yuki-53 commented on service/api/views.py
> +async def check_key(
Добавил

2022-11-25 19:06 UTC, Yuki-53 commented on tests/api/test_views.py
> +from requests.structures import CaseInsensitiveDict
Удалил

2022-11-26 08:02 UTC, groundmax approved these changes

2022-11-26 08:02 UTC, groundmax commented
Все ок, только нюанс, почему у вас CI/CD не работает?

2022-11-29 17:41 UTC, Yuki-53 commented
> Все ок, только нюанс, почему у вас CI/CD не работает?

Теперь работает. Только пришлось обратно добавить CaseInsensitiveDict, без него тесты не проходили

2022-11-29 23:12 UTC, groundmax approved these changes

2022-11-30 09:45 UTC, merged